/* Fuzzy inference system generated by qfiscgen.m for the qFIS engine*/
/* Generated : 24-Sep-2024 18:18:47 */
/* MATLAB Version: 9.10.0.1602886 (R2021a) */
/* Note: Based on the qFIS engine from https://github.com/kmilo17pet/qlibs */

#ifndef MATANG1_FIS_H
#define MATANG1_FIS_H

#ifdef __cplusplus
    extern "C" {
#endif

    void matang1_init( void );
    void matang1_run( float *inputs, float *outputs );

#ifdef __cplusplus
    }
#endif

#endif /* MATANG1_FIS_H */
